language: python
python:
  - "2.7"

install:
- pip install -r tests/requirements.txt

script:
- python -m flake8 --max-line-length=110 oeg_infotech
- python -m coverage run tests/run_tests.py
- python -m coveralls
- python -m coverage report --skip-covered
