language: python
python:
  - "2.7"

install:
- pip install -r tests/requirements.txt

script:
- python -m flake8 --max-line-length=120 oeg_infotech
- pytest --cov=oeg_infotech --cov-report term:skip-covered --durations=5 tests
- python -m coveralls
